### ISSUE TITLE
Wrong floating text

### ISSUE THREAD

**Issue by UnEnanoMas** [jasonwynn10/MyPlot#355]
### Issue description

- Expected result: What were you expecting to happen? That the /p buy does not appear if the plot is not for sale by another player
- Actual result: What actually happened? If the player claims a plot in this new version, another player enters and it will appear that he can buy it (without the other player having put it up for sale)

### Steps to reproduce the issue
1. Update MyPlot to the latest version
2. A player buys a plot
3. If another player enters inside, it will appear that he can buy it
4. (This is only visual, if the player puts the command / p buy the following message will appear "You can't buy a plot from yourself" (The message is also wrong because the plot is not from that player)

### OS and versions

* Plugin Version: Dev #655
* PocketMine-MP: 3.15.2
* PHP: 7.3
* Game version: PE/Win10 

### Other Plugins

- If you remove all other plugins, does the issue still occur? I dont know
- If the issue is **not** reproducible without other plugins: 
  - Have you asked for help in the community discord before creating an issue? No
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section.

**Comment by UnEnanoMas** [comment]
![Captura de pantalla (357)](https://user-images.githubusercontent.com/63286108/96946911-efe6a780-14e1-11eb-90cc-36f104c37c5d.png)
![Captura de pantalla (358)](https://user-images.githubusercontent.com/63286108/96946918-f4ab5b80-14e1-11eb-867f-297b567bbbab.png)

**Comment by DragonfireHD** [comment]
Same problem

**Comment by jasonwynn10** [comment]
fixed in 2d8adaffe983dcee4c96c0157a81073ed4a31bb9

**Comment by UnEnanoMas** [comment]
Tomorrow I test it, I'm going to sleep

**Comment by UnEnanoMas** [comment]
The parcels that were purchased in the past version still have the visual error.

The plots that are bought new work correctly and put the correct message.

#Dev658

@jasonwynn10

**Comment by jasonwynn10** [comment]
Please clarify what you mean

**Comment by UnEnanoMas** [comment]
Plots that have been purchased with version # 655 # 656 and # 657 have the wrong text when you enter.

But those that are purchased now in version # 658 work correctly

**Comment by jasonwynn10** [comment]
Ok so it is resolved then 👍
